export const fontFamilyOptions = [
  "",
  "Arial",
  "Times New Roman",
  "Calibri",
  "Cambria",
  "Verdana",
  "Tahoma",
  "Courier New",
  "Georgia",
  "Trebuchet MS",
  "Palatino Linotype",
  "Century Gothic",
  "Franklin Gothic Medium",
  "Garamond",
  "Book Antiqua",
  "Lucida Sans Unicode",
  "Helvetica",
  "Impact",
  "Baskerville",
  "Futura",
  "Gill Sans",
  "Myriad Pro",
  "Optima",
  "Rockwell",
  "Segoe UI",
  "Univers",
  "Century Schoolbook",
  "Copperplate Gothic",
  "Brush Script",
  "Eurostile",
  "Trajan Pro",
  "Arial Black",
  "Franklin Gothic Heavy",
  "Goudy Old Style",
  "Haettenschweiler",
  "Bookman Old Style",
  "Copperplate",
  "Didot",
  "Lucida Console",
  "Lucida Handwriting",
  "Mistral",
  "Monotype Corsiva",
  "Perpetua",
  "Ravie",
  "Segoe Print",
  "Stencil",
  "Franklin Gothic Book",
  "Century",
  "Bell MT",
  "Elephant",
  "Old English Text MT",
  "Vivaldi",
  "Palace Script MT",
  "Kunstler Script",
  "Papyrus",
  "Lucida Bright",
  "Lucida Fax",
  "Lucida Sans",
  "Lucida Sans Typewriter",
  "Andale Mono",
  "Bell Gothic",
  "Arial Narrow",
  "Century Schoolbook",
  "Chiller",
  "Corbel",
  "Constantia",
  "MS Gothic",
  "MS Mincho",
  "Rockwell Extra Bold",
  "Segoe Script",
  "Times",
  "Symbol",
  "Wingdings",
  "Wingdings 2",
  "Wingdings 3",
  "Century Gothic",
  "Monotype Corsiva",
  "Arial Rounded MT Bold",
  "Kristen ITC",
  "Broadway",
  "Courier New",
  "Lucida Console",
  "Lucida Sans Unicode",
  "Segoe UI Symbol",
  "Copperplate Gothic Bold",
  "Franklin Gothic Medium Cond",
  "Gabriola",
  "Segoe UI Historic",
  "Showcard Gothic",
  "Tw Cen MT",
  "Tw Cen MT Condensed",
  "Viner Hand ITC",
  "Lucida Bright",
  "Lucida Sans"
];
